import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import PageLoader from "@/components/PageLoader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-slate-300 antialiased">
        <PageLoader />
        <header className="sticky top-0 backdrop-blur z-50 border-b lg:mb-20 mb-10">
          <Navbar />
        </header>
        <main className="max-w-5xl mx-auto px-0 lg:px-6 py-12">{children}</main>
        <footer className="border-t mt-12 py-6 text-center text-sm text-slate-500">
          © {new Date().getFullYear()} Soham Das — Built with Next.js + Tailwind
          + Framer Motion
        </footer>
      </body>
    </html>
  );
}
